apiVersion: v1
kind: Service
metadata:
  name: eventstore
  namespace: {{ .Values.global.namespaceOverride }}
spec:
  type: LoadBalancer
  ports:
    - name: eventstore
      port: 1113
      targetPort: 1113
    - name: http
      port: 2113
      targetPort: 2113
  selector:
    app: eventstore
